uc-cdis/dcf-dataservice

jobs/aws-bucket-replicate-job.yaml, scripts/aws_replicate.py, scripts/settings.py
Make aws cli run faster by increasing the maximum number of concurrent requests and queue size
https://docs.aws.amazon.com/cli/latest/topic/s3-config.html
https://stackoverflow.com/questions/4663016/faster-s3-bucket-duplication/23577621
=> feat(config): set aws config

.gitignore, README.md, scripts/aws_replicate.py, scripts/deletion.py, scripts/google_compose_upload.py, scripts/google_replicate.py, scripts/indexd_utils.py, scripts/replicate.py, scripts/utils.py, tests/test_replicate.py
Update Readme
more log
refactor
fix indexd update for acl changes
=> fix indexd and refactor

scripts/aws_replicate.py, scripts/deletion.py, scripts/replicate.py
comment the code for aws redact. Only do gs redact this time. Remember to uncomment for next redact phrase
=> feat(gs_redact): only do gs redact

.gitignore, jobs/aws-bucket-replicate-job.yaml, jobs/google-bucket-replicate-job.yaml, jobs/kube-setup-scripts.sh, scripts/utils.py
rename some secret
provide ignored file path args
=> feat(jobs): fix jobs.yaml

jobs/google-bucket-replicate-job.yaml, scripts/aws_replicate.py
Fix the quite weird error of boto3 by using global session
https://github.com/boto/boto3/issues/801
=> fix(client): fix client session

dev-requirements.txt, jobs/aws-bucket-replicate-job.yaml, jobs/google-bucket-replicate-job.yaml, scripts/aws_replicate.py, scripts/google_replicate.py, scripts/replicate.py, scripts/utils.py, tests/test_replicate.py
Support passing release version for job commands
Support resumable logs for aws replicate
Support saving logs for each release
=> feat(log): support resumable logs

scripts/aws_replicate.py
Let's using aws cli as default if object class is not glacier or deep archive
=> feat(storage_class): refactor handling storage class logic

scripts/aws_replicate.py, scripts/validate.py
=> fix(s3_session): use correct session

scripts/validate.py
=> fix(column order): fix manifest column order

dataflow_pipeline.py, jobs/aws-bucket-replicate-job.yaml, jobs/google-bucket-replicate-job.yaml, jobs/replicate-validation-job.yaml, scripts/aws_replicate.py, scripts/google_replicate.py, scripts/validate.py
Change the log name for each manifest
- instead of using `log.txt` as the name, use the name with prefix from the manifest name
- only generate augmented manifest if passing validation
=> feat(dcf): only save to tsv if pass validation

jobs/google-bucket-replicate-job.yaml, jobs/remove-objects-from-clouds-job.yaml, scripts/deletion.py, scripts/replicate.py
=> feat(log_bucket): make sure log bucket exists

scripts/validate.py
=> fix(space): fix spaces

scripts/utils.py
=> chore(log): more logs

scripts/google_replicate.py
Change log interval so that the service produces less logs
=> fix(log): increase log interval

jobs/replicate-validation-job.yaml, scripts/google_replicate.py, scripts/validate.py, tests/test_replicate.py
- Retry logic for google replicate
=> feat(retry): add retry logic

scripts/validate.py
=> fix(bug): fix minor

jobs/google-bucket-replicate-job.yaml, requirements.txt, scripts/aws_replicate.py, scripts/deletion.py, scripts/google_compose_upload.py, scripts/google_replicate.py, scripts/indexd_utils.py, scripts/requirements.txt, scripts/utils.py, scripts/validate.py
`decode` function does not exit in python 3. Replace with `hex()`
Add `retry` decorator
re-index files that are not indexed
=> fix(decode): fix decode function in python 3

scripts/deletion.py, scripts/indexd_utils.py
fix small bug when removing records from indexd
=> fix(indexd): remove record from indexd

scripts/aws_replicate.py
=> chore(message): just warning not error

scripts/google_replicate.py, scripts/settings.py
- parameterized DATA_ENDPT in settings.py
=> parameterized DATA_ENDPT

scripts/google_replicate.py
=> fix(typos): fix typos

jobs/kube-setup-scripts.sh
=> feat(setup):make easier setup

scripts/aws_replicate.py
- Added support for cgci bucket
- Added support for tcga controlled bucket
=> cgci_support

scripts/aws_replicate.py, scripts/utils.py, tests/test_replicate.py
- changed tests
- changed tcga reverse acl
- added cgci reverse acl
=> reverse_acl_tcga_fixes

scripts/utils.py
- cgci support to get_aws_bucket_name
=> get_bucket_name_cgci

jobs/google-bucket-replicate-job.yaml
- Proxy for now due to issues with squid.
=> export_proxy

dataflow_pipeline.py, replicate.py, scripts/aws_replicate.py, scripts/deletion.py, scripts/google_compose_upload.py, scripts/google_replicate.py, scripts/indexd_utils.py, scripts/utils.py, scripts/validate.py, tests/test_replicate.py
- Added bucket name fixes for `beatml-cohort` and `organic-pancreatic`.
=> Chore: Add bucket naming + black

scripts/aws_replicate.py, scripts/utils.py, tests/test_replicate.py
- Add missing bucket names to `reverse_acl` and `get_aws_bucket_name`
=> Fix: Add bucket name in utils

README.md
=> chore(readme): update readme.md

scripts/aws_replicate.py, scripts/utils.py, tests/test_replicate.py
- Added support for CMI projects.
- Added list for buckets that have both -2-open and -2-controlled postfix
- Added list for buckets that have -open and -controlled postfix
=> Add support for CMI project

scripts/aws_replicate.py
- Fix postfix logic for buckets under different accounts.
=> Fix postfix exception

scripts/aws_replicate.py, scripts/validate.py
- Enable bucket-owner-full-control flag
=> feat(bucket-owner-full-control): enable acl flag

scripts/aws_replicate.py
- Fix aws replicate not using parameterized data endpoint.
=> Fix aws not using parameterized data endpoint

scripts/validate.py
- Add missing botocore import 
- Add missing `bucket_name` variable and path
=> (Fix): preliminary check

.pre-commit-config.yaml, .travis.yml, dataflow_pipeline.py, scripts/google_compose_upload.py, scripts/validate.py, tests/test_imports.py, tests/test_replicate.py
- Fix urllib import error
- Pin pip<20.3 in travis 
- Add import tests
=> Fix urllib import error

scripts/validate.py
- Fix aws validation always showing "object not copied to bucket"
=> Fix multiple bucket check

scripts/aws_replicate.py, scripts/utils.py
Added exception to other hardcoded areas
=> PXP-5167: DR29

scripts/validate.py
- Fix incorrent loggin keyword from `indexd_urls` to `indexd_url`
=> (fix): Fix logging using wrong key

.github/workflows/image_build_push.yaml, Dockerfile, dataflow_pipeline.py, requirements.txt, scripts/aws_replicate.py, scripts/deletion.py, scripts/requirements.txt, setup.py
- Fix delete objects request body
- redaction wasn't deleting indexd records unless the gs or s3 url was still active, it would error out on the exception due to misnamed error property
=> PXP-10112: Fix redaction script

replicate.py, scripts/settings.py
- Implemented slack webhook, send notification at beginning and completion of scripts. Webhook URL configuration in dcf_dataservice_settings file on dcfprod.
=> PXP-9416: Add Slack Webhook

scripts/deletion.py
Fix bug in code which returns false for dry_run even when there are records to delete
- Implemented code change to run aws deletion func during dry run, houses logic for whether to fully delete or not during a dry_run
Code must have aws url for every gs url, checks for aws and if found decides it should be deleted
=> PXP-10390: Fix redaction dry_run

scripts/deletion.py
Reverts uc-cdis/dcf-dataservice#114
=> Revert "PXP-10390: Fix redaction dry_run"

.travis.yml, dcfdataservice/deletion.py
https://ctds-planx.atlassian.net/browse/DCF-2024
- provide proper param for s3 to successfully delete objects from buckets
=> DCF-2024: Update deletion.py for redaction

dcfdataservice/indexd_utils.py
https://ctds-planx.atlassian.net/browse/DCF-2036
add try catch to work with retry annotation
=> add try catch to work with retry annotation
